### ISSUE TITLE
Some security findings

### ISSUE THREAD

**Issue by cainbyrne** [micromatch/to-regex-range#13]
Hi Team,

Don’t you just hate it when someone includes your open source project, only to run some scanning tools and come back with issues?  Yea we do too.

So we’ve been running lots of security scans on open source projects, including yours, through some automation we built.  Don’t worry, it took less than a few minutes to run the scans and auto-generate the report.

Wasn’t sure how to send it to you, so we’ve stuck them up at https://source-security.co.uk/5adf9436-be90-4221-bdf6-4a3c4bcb2f23/ so you can see if anything needs handled.  Feel free to re-run the security scanning anytime you like, it’s free for open source.

Best of luck,

Cain

**Comment by jonschlinkert** [comment]
Thanks @cainbyrne! You've been reported as a fake troll account, and blocked.
