### ISSUE TITLE
comma formatted number support

### ISSUE THREAD

**Issue by HeGanjie** [micromatch/to-regex-range#2]
for example, `toRegexRange(1000, 2000, options)` can match `1,234`

**Comment by jonschlinkert** [comment]
I've considered adding support for commas, but some locales use spaces or dots as separators, and there are a number of potential edge cases. 

I think this is something that should be handled before passing the number to `to-regex-range`, but I would be open to a pull request if sufficient unit tests are added.

**Comment by jonschlinkert** [comment]
closing due to lack of reply

**Comment by HeGanjie** [comment]
Thank you for reply, I have found another way to solve my matching problem. But this package is still impresses me.
