### ISSUE TITLE
Question about the usage of countZeros

### ISSUE THREAD

**Issue by zwcn** [micromatch/to-regex-range#8]
Hi,

I'm wondering about the call of `countZeros` at Line https://github.com/micromatch/to-regex-range/blob/master/index.js#L109. It seems to me that the intention of `countZeros` is to replace the last `zeros` digits of the `integer` with 0s. Why is `max + 1` passed as an input instead of `max`? If `max` is 9 and `zeros` is 1, then `countZeros(10, 1)` would return 10, which conflicts with my understanding of the intention of `countZeros`. Am I missing something?

**Comment by jonschlinkert** [comment]
@zwcn sounds very good question. I won't pretend to remember, I'd need to get re-familiarized with the code. Maybe pull down the repo and inspect the code if you have some time. If you see something that isn't working, a PR would be greatly appreciated.

**Comment by zwcn** [comment]
@jonschlinkert Sure, I'll inspect the code more closely. If you remember something, please let me know. Thanks!
